### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by burkesquires** [ourcodingclub/CC-2-RMarkdown#1]
Hello,
The materials look great. I would be interested in passing them along (with attribution) in a course I am teaching but cannot until a license has been added. Please add a license so I and others know if sharing is possible.

Regards

**Comment by johngodlee** [comment]
Hi, thanks for bringing this up. I hadn't thought about licensing until now. I've added a CC-BY-NC-SA license for now. So you are more than welcome to use our teaching materials in your class. 

Can I ask what the course is and where you will be teaching it? We're always looking for new collaborators and opportunities to expand our network of coding clubs.
